[package]
name = "diesel_reset"
version = "0.1.0"
authors = ["Henry Zimmerman <zimhen7@gmail.com>"]
edition = "2018"

[dependencies]

migrations_internals = "~1.4.0"
lazy_static = "1.0"
diesel = { version = "1.4.1", features = ["postgres", "r2d2"] }

