[package]
name = "authorization"
version = "0.1.0"
authors = ["Henry Zimmerman <zimhen7@gmail.com>"]
edition = "2018"

[dependencies]
warp = "0.1.13"
frank_jwt = "3.1.0"
chrono = {version="0.4.6", features=["serde"]}
serde = {version="1.0.85", features=["derive"]}
serde_json = "1.0.37"
