[package]
name = "diesel_test_setup"
version = "0.1.0"
authors = ["Henry Zimmerman <zimhen7@gmail.com>"]
edition = "2018"

[dependencies]

migrations_internals = "1.4.0"
lazy_static = "1.3.0"
diesel = { version = "1.4.2", features = ["postgres", "r2d2"] }
nanoid = "0.2.0"

